name: Pull Request CI
on:
  pull_request:
    branches:
      - 2.x-natives

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Version Info
        run: mvn -version
      - name: Build with Maven and nmake
        run: |
          call "%VCVARS%"
          mvn -B package --file pom.xml
